# Generated by Django 5.1 on 2024-08-12 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.IntegerField(primary_key=True, serialize=False)),
                ('last_name', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=20)),
                ('title', models.CharField(blank=True, max_length=30, null=True)),
                ('birth_date', models.DateTimeField(blank=True, null=True)),
                ('hire_date', models.DateTimeField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=70, null=True)),
                ('city', models.CharField(blank=True, max_length=40, null=True)),
                ('state', models.CharField(blank=True, max_length=40, null=True)),
                ('country', models.CharField(blank=True, max_length=40, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True)),
                ('phone', models.CharField(blank=True, max_length=24, null=True)),
                ('fax', models.CharField(blank=True, max_length=24, null=True)),
                ('email', models.CharField(blank=True, max_length=60, null=True)),
                ('reports_to', models.ForeignKey(blank=True, db_column='reports_to', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='employees.employee')),
            ],
            options={
                'db_table': 'employee',
            },
        ),
    ]
