# Generated by Django 5.1 on 2024-08-12 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('track', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('playlist_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
            ],
            options={
                'db_table': 'playlist',
            },
        ),
        migrations.CreateModel(
            name='PlaylistTrack',
            fields=[
                ('playlist', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='playlists.playlist')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='track.track')),
            ],
            options={
                'db_table': 'playlist_track',
                'unique_together': {('playlist', 'track')},
            },
        ),
    ]
