# Generated by Django 5.1 on 2024-08-12 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0002_alter_playlisttrack_playlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlisttrack',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='playlisttrack',
            name='playlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='playlists.playlist'),
        ),
    ]
