# Generated by Django 5.1 on 2024-08-12 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0003_playlisttrack_id_alter_playlisttrack_playlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlisttrack',
            name='id',
        ),
        migrations.AlterField(
            model_name='playlisttrack',
            name='playlist',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='playlists.playlist'),
        ),
    ]
