# Generated by Django 5.0 on 2024-08-14 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0004_remove_playlisttrack_id_alter_playlisttrack_playlist'),
        ('track', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlisttrack',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='track', to='track.track'),
        ),
    ]
