# Generated by Django 5.0 on 2024-08-17 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0002_alter_track_genre_alter_track_track_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='track_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
