# Generated by Django 5.0 on 2024-08-17 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0003_alter_track_track_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='track',
            old_name='media_type',
            new_name='media_format',
        ),
    ]
