# Generated by Django 5.0 on 2024-08-17 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0004_rename_media_type_track_media_format'),
    ]

    operations = [
        migrations.RenameField(
            model_name='track',
            old_name='media_format',
            new_name='media_type',
        ),
    ]
