# Generated by Django 5.0 on 2024-08-18 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0005_rename_media_format_track_media_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='track.genre'),
        ),
    ]
